import type { NextPage } from 'next'
import Head from 'next/head'
import { useEditionQuery } from '@public-assembly/zora-editions-audio-minter'

const Home: NextPage = () => {
  const { data } = useEditionQuery('0x674fb9ed86b847db9aee0a19e9055d5d2c0e6cc4')
  
  return (
    <div>
      <Head>
        {/*
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        */}
      </Head>
      <div>{JSON.stringify(data, null, 2)}</div>
    </div>
  )
}

export default Home
